// Code generated by protoc-gen-go. DO NOT EDIT.
// source: game_protocol.proto

package game_protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Entity struct {
	Id      uint32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Created float64 `protobuf:"fixed64,2,opt,name=created,proto3" json:"created,omitempty"`
	PosX    float32 `protobuf:"fixed32,3,opt,name=pos_x,json=posX,proto3" json:"pos_x,omitempty"`
	PosY    float32 `protobuf:"fixed32,4,opt,name=pos_y,json=posY,proto3" json:"pos_y,omitempty"`
	// Used for client side prediction of next position
	VelX float32 `protobuf:"fixed32,5,opt,name=vel_x,json=velX,proto3" json:"vel_x,omitempty"`
	VelY float32 `protobuf:"fixed32,6,opt,name=vel_y,json=velY,proto3" json:"vel_y,omitempty"`
	// Visual direction
	DirX float32 `protobuf:"fixed32,7,opt,name=dir_x,json=dirX,proto3" json:"dir_x,omitempty"`
	DirY float32 `protobuf:"fixed32,8,opt,name=dir_y,json=dirY,proto3" json:"dir_y,omitempty"`
	// Renderables are ids of different ways the object sould be rendered,
	// for example as a cloud of smoke or a texture.
	Renderable           []uint32 `protobuf:"varint,9,rep,packed,name=renderable,proto3" json:"renderable,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Entity) Reset()         { *m = Entity{} }
func (m *Entity) String() string { return proto.CompactTextString(m) }
func (*Entity) ProtoMessage()    {}
func (*Entity) Descriptor() ([]byte, []int) {
	return fileDescriptor_72c54c60985a8efc, []int{0}
}

func (m *Entity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Entity.Unmarshal(m, b)
}
func (m *Entity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Entity.Marshal(b, m, deterministic)
}
func (m *Entity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Entity.Merge(m, src)
}
func (m *Entity) XXX_Size() int {
	return xxx_messageInfo_Entity.Size(m)
}
func (m *Entity) XXX_DiscardUnknown() {
	xxx_messageInfo_Entity.DiscardUnknown(m)
}

var xxx_messageInfo_Entity proto.InternalMessageInfo

func (m *Entity) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Entity) GetCreated() float64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *Entity) GetPosX() float32 {
	if m != nil {
		return m.PosX
	}
	return 0
}

func (m *Entity) GetPosY() float32 {
	if m != nil {
		return m.PosY
	}
	return 0
}

func (m *Entity) GetVelX() float32 {
	if m != nil {
		return m.VelX
	}
	return 0
}

func (m *Entity) GetVelY() float32 {
	if m != nil {
		return m.VelY
	}
	return 0
}

func (m *Entity) GetDirX() float32 {
	if m != nil {
		return m.DirX
	}
	return 0
}

func (m *Entity) GetDirY() float32 {
	if m != nil {
		return m.DirY
	}
	return 0
}

func (m *Entity) GetRenderable() []uint32 {
	if m != nil {
		return m.Renderable
	}
	return nil
}

type Update struct {
	// Used to keep update order and to calulate
	Time                 float64   `protobuf:"fixed64,1,opt,name=time,proto3" json:"time,omitempty"`
	Update               []*Entity `protobuf:"bytes,2,rep,name=update,proto3" json:"update,omitempty"`
	Remove               []uint32  `protobuf:"varint,3,rep,packed,name=remove,proto3" json:"remove,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Update) Reset()         { *m = Update{} }
func (m *Update) String() string { return proto.CompactTextString(m) }
func (*Update) ProtoMessage()    {}
func (*Update) Descriptor() ([]byte, []int) {
	return fileDescriptor_72c54c60985a8efc, []int{1}
}

func (m *Update) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Update.Unmarshal(m, b)
}
func (m *Update) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Update.Marshal(b, m, deterministic)
}
func (m *Update) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Update.Merge(m, src)
}
func (m *Update) XXX_Size() int {
	return xxx_messageInfo_Update.Size(m)
}
func (m *Update) XXX_DiscardUnknown() {
	xxx_messageInfo_Update.DiscardUnknown(m)
}

var xxx_messageInfo_Update proto.InternalMessageInfo

func (m *Update) GetTime() float64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *Update) GetUpdate() []*Entity {
	if m != nil {
		return m.Update
	}
	return nil
}

func (m *Update) GetRemove() []uint32 {
	if m != nil {
		return m.Remove
	}
	return nil
}

func init() {
	proto.RegisterType((*Entity)(nil), "Entity")
	proto.RegisterType((*Update)(nil), "Update")
}

func init() { proto.RegisterFile("game_protocol.proto", fileDescriptor_72c54c60985a8efc) }

var fileDescriptor_72c54c60985a8efc = []byte{
	// 234 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0xd0, 0xc1, 0x6a, 0xc3, 0x20,
	0x18, 0x07, 0x70, 0x34, 0xa9, 0xd9, 0xbe, 0xd1, 0x1d, 0x2c, 0x8c, 0xef, 0xb4, 0x49, 0x4f, 0x9e,
	0x7a, 0xd8, 0x9e, 0x61, 0x2f, 0x20, 0x14, 0xd2, 0x53, 0x48, 0xeb, 0xc7, 0x10, 0x92, 0x1a, 0xac,
	0x0b, 0xc9, 0x5b, 0xee, 0x91, 0xc6, 0x4c, 0x0d, 0xbb, 0xfd, 0xff, 0x3f, 0x45, 0xf8, 0x0b, 0xbb,
	0xaf, 0xb6, 0xa7, 0x66, 0x08, 0x3e, 0xfa, 0x8b, 0xef, 0x0e, 0x29, 0xec, 0x7f, 0x18, 0x88, 0xcf,
	0x6b, 0x74, 0x71, 0x96, 0xcf, 0xc0, 0x9d, 0x45, 0xa6, 0x98, 0xde, 0x1a, 0xee, 0xac, 0x44, 0xa8,
	0x2e, 0x81, 0xda, 0x48, 0x16, 0xb9, 0x62, 0x9a, 0x99, 0x5c, 0xe5, 0x0e, 0x36, 0x83, 0xbf, 0x35,
	0x13, 0x16, 0x8a, 0x69, 0x6e, 0xca, 0xc1, 0xdf, 0xea, 0x8c, 0x33, 0x96, 0x2b, 0x9e, 0xfe, 0x70,
	0xa4, 0xae, 0x99, 0x70, 0xb3, 0xe0, 0x48, 0x5d, 0x9d, 0x71, 0x46, 0xb1, 0x62, 0xba, 0x69, 0x5d,
	0x68, 0x26, 0xac, 0x16, 0xb4, 0x2e, 0xd4, 0x19, 0x67, 0x7c, 0x58, 0xf1, 0x24, 0x5f, 0x01, 0x02,
	0x5d, 0x2d, 0x85, 0xf6, 0xdc, 0x11, 0x3e, 0xaa, 0x42, 0x6f, 0xcd, 0x3f, 0xd9, 0x1f, 0x41, 0x1c,
	0x07, 0xdb, 0x46, 0x92, 0x12, 0xca, 0xe8, 0x7a, 0x4a, 0x9b, 0x98, 0x49, 0x59, 0xbe, 0x81, 0xf8,
	0x4e, 0xa7, 0xc8, 0x55, 0xa1, 0x9f, 0xde, 0xab, 0xc3, 0x32, 0xdf, 0xdc, 0x59, 0xbe, 0x80, 0x08,
	0xd4, 0xfb, 0x91, 0xb0, 0x48, 0x4f, 0xdf, 0xdb, 0x59, 0xa4, 0x0f, 0xfb, 0xf8, 0x0d, 0x00, 0x00,
	0xff, 0xff, 0x3c, 0x52, 0x69, 0x90, 0x47, 0x01, 0x00, 0x00,
}
