// Code generated by protoc-gen-go. DO NOT EDIT.
// source: game_protocol.proto

package game_protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Action int32

const (
	Action_NOTHING Action = 0
	Action_GUN     Action = 1
)

var Action_name = map[int32]string{
	0: "NOTHING",
	1: "GUN",
}

var Action_value = map[string]int32{
	"NOTHING": 0,
	"GUN":     1,
}

func (x Action) String() string {
	return proto.EnumName(Action_name, int32(x))
}

func (Action) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_72c54c60985a8efc, []int{0}
}

type Entity struct {
	Id      uint32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Created float64 `protobuf:"fixed64,2,opt,name=created,proto3" json:"created,omitempty"`
	PosX    float32 `protobuf:"fixed32,3,opt,name=pos_x,json=posX,proto3" json:"pos_x,omitempty"`
	PosY    float32 `protobuf:"fixed32,4,opt,name=pos_y,json=posY,proto3" json:"pos_y,omitempty"`
	// Used for client side prediction of next position
	VelX float32 `protobuf:"fixed32,5,opt,name=vel_x,json=velX,proto3" json:"vel_x,omitempty"`
	VelY float32 `protobuf:"fixed32,6,opt,name=vel_y,json=velY,proto3" json:"vel_y,omitempty"`
	// Visual direction
	DirX float32 `protobuf:"fixed32,7,opt,name=dir_x,json=dirX,proto3" json:"dir_x,omitempty"`
	DirY float32 `protobuf:"fixed32,8,opt,name=dir_y,json=dirY,proto3" json:"dir_y,omitempty"`
	// Renderables are ids of different ways the object sould be rendered,
	// for example as a cloud of smoke or a texture.
	Renderable []*Renderable `protobuf:"bytes,9,rep,name=renderable,proto3" json:"renderable,omitempty"`
	// player names and chat bars
	Name                 string   `protobuf:"bytes,10,opt,name=name,proto3" json:"name,omitempty"`
	Chat                 string   `protobuf:"bytes,11,opt,name=chat,proto3" json:"chat,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Entity) Reset()         { *m = Entity{} }
func (m *Entity) String() string { return proto.CompactTextString(m) }
func (*Entity) ProtoMessage()    {}
func (*Entity) Descriptor() ([]byte, []int) {
	return fileDescriptor_72c54c60985a8efc, []int{0}
}

func (m *Entity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Entity.Unmarshal(m, b)
}
func (m *Entity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Entity.Marshal(b, m, deterministic)
}
func (m *Entity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Entity.Merge(m, src)
}
func (m *Entity) XXX_Size() int {
	return xxx_messageInfo_Entity.Size(m)
}
func (m *Entity) XXX_DiscardUnknown() {
	xxx_messageInfo_Entity.DiscardUnknown(m)
}

var xxx_messageInfo_Entity proto.InternalMessageInfo

func (m *Entity) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Entity) GetCreated() float64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *Entity) GetPosX() float32 {
	if m != nil {
		return m.PosX
	}
	return 0
}

func (m *Entity) GetPosY() float32 {
	if m != nil {
		return m.PosY
	}
	return 0
}

func (m *Entity) GetVelX() float32 {
	if m != nil {
		return m.VelX
	}
	return 0
}

func (m *Entity) GetVelY() float32 {
	if m != nil {
		return m.VelY
	}
	return 0
}

func (m *Entity) GetDirX() float32 {
	if m != nil {
		return m.DirX
	}
	return 0
}

func (m *Entity) GetDirY() float32 {
	if m != nil {
		return m.DirY
	}
	return 0
}

func (m *Entity) GetRenderable() []*Renderable {
	if m != nil {
		return m.Renderable
	}
	return nil
}

func (m *Entity) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Entity) GetChat() string {
	if m != nil {
		return m.Chat
	}
	return ""
}

type Renderable struct {
	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// RGBA
	Color                uint32   `protobuf:"varint,2,opt,name=color,proto3" json:"color,omitempty"`
	Size                 float32  `protobuf:"fixed32,3,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Renderable) Reset()         { *m = Renderable{} }
func (m *Renderable) String() string { return proto.CompactTextString(m) }
func (*Renderable) ProtoMessage()    {}
func (*Renderable) Descriptor() ([]byte, []int) {
	return fileDescriptor_72c54c60985a8efc, []int{1}
}

func (m *Renderable) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Renderable.Unmarshal(m, b)
}
func (m *Renderable) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Renderable.Marshal(b, m, deterministic)
}
func (m *Renderable) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Renderable.Merge(m, src)
}
func (m *Renderable) XXX_Size() int {
	return xxx_messageInfo_Renderable.Size(m)
}
func (m *Renderable) XXX_DiscardUnknown() {
	xxx_messageInfo_Renderable.DiscardUnknown(m)
}

var xxx_messageInfo_Renderable proto.InternalMessageInfo

func (m *Renderable) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Renderable) GetColor() uint32 {
	if m != nil {
		return m.Color
	}
	return 0
}

func (m *Renderable) GetSize() float32 {
	if m != nil {
		return m.Size
	}
	return 0
}

type Update struct {
	// Used to keep update order and to calulate
	Time   float64   `protobuf:"fixed64,1,opt,name=time,proto3" json:"time,omitempty"`
	Entity []*Entity `protobuf:"bytes,2,rep,name=entity,proto3" json:"entity,omitempty"`
	// ids of entities to remove
	Remove               []uint32 `protobuf:"varint,3,rep,packed,name=remove,proto3" json:"remove,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Update) Reset()         { *m = Update{} }
func (m *Update) String() string { return proto.CompactTextString(m) }
func (*Update) ProtoMessage()    {}
func (*Update) Descriptor() ([]byte, []int) {
	return fileDescriptor_72c54c60985a8efc, []int{2}
}

func (m *Update) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Update.Unmarshal(m, b)
}
func (m *Update) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Update.Marshal(b, m, deterministic)
}
func (m *Update) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Update.Merge(m, src)
}
func (m *Update) XXX_Size() int {
	return xxx_messageInfo_Update.Size(m)
}
func (m *Update) XXX_DiscardUnknown() {
	xxx_messageInfo_Update.DiscardUnknown(m)
}

var xxx_messageInfo_Update proto.InternalMessageInfo

func (m *Update) GetTime() float64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *Update) GetEntity() []*Entity {
	if m != nil {
		return m.Entity
	}
	return nil
}

func (m *Update) GetRemove() []uint32 {
	if m != nil {
		return m.Remove
	}
	return nil
}

type Status struct {
	// identify the player
	PlayerId uint64 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	// Used to signal what direction player moves in
	VelX float32 `protobuf:"fixed32,2,opt,name=vel_x,json=velX,proto3" json:"vel_x,omitempty"`
	VelY float32 `protobuf:"fixed32,3,opt,name=vel_y,json=velY,proto3" json:"vel_y,omitempty"`
	DirX float32 `protobuf:"fixed32,4,opt,name=dir_x,json=dirX,proto3" json:"dir_x,omitempty"`
	DirY float32 `protobuf:"fixed32,5,opt,name=dir_y,json=dirY,proto3" json:"dir_y,omitempty"`
	// Actions
	Action               []Action `protobuf:"varint,6,rep,packed,name=action,proto3,enum=game_protocol.Action" json:"action,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_72c54c60985a8efc, []int{3}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetPlayerId() uint64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *Status) GetVelX() float32 {
	if m != nil {
		return m.VelX
	}
	return 0
}

func (m *Status) GetVelY() float32 {
	if m != nil {
		return m.VelY
	}
	return 0
}

func (m *Status) GetDirX() float32 {
	if m != nil {
		return m.DirX
	}
	return 0
}

func (m *Status) GetDirY() float32 {
	if m != nil {
		return m.DirY
	}
	return 0
}

func (m *Status) GetAction() []Action {
	if m != nil {
		return m.Action
	}
	return nil
}

func init() {
	proto.RegisterEnum("game_protocol.Action", Action_name, Action_value)
	proto.RegisterType((*Entity)(nil), "game_protocol.Entity")
	proto.RegisterType((*Renderable)(nil), "game_protocol.Renderable")
	proto.RegisterType((*Update)(nil), "game_protocol.Update")
	proto.RegisterType((*Status)(nil), "game_protocol.Status")
}

func init() { proto.RegisterFile("game_protocol.proto", fileDescriptor_72c54c60985a8efc) }

var fileDescriptor_72c54c60985a8efc = []byte{
	// 394 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xcf, 0x6e, 0xd4, 0x30,
	0x10, 0xc6, 0xb1, 0x93, 0x38, 0xdd, 0x59, 0xa5, 0xaa, 0x5c, 0x40, 0x46, 0x48, 0x28, 0xca, 0x29,
	0x42, 0x6a, 0x0f, 0x70, 0xe2, 0x08, 0x12, 0xb4, 0xbd, 0x2c, 0x92, 0xa1, 0xd2, 0xf6, 0x14, 0xb9,
	0xb1, 0x05, 0x96, 0x92, 0x38, 0x72, 0xcc, 0x6a, 0xc3, 0x6b, 0xf0, 0x12, 0x3c, 0x26, 0x8a, 0xf3,
	0xa7, 0x2d, 0xbb, 0xb7, 0x6f, 0x7e, 0xf9, 0x32, 0xe3, 0x99, 0x0f, 0xce, 0x7f, 0x88, 0x5a, 0x15,
	0xad, 0x35, 0xce, 0x94, 0xa6, 0xba, 0xf4, 0x82, 0x26, 0x4f, 0x60, 0xf6, 0x07, 0x03, 0xf9, 0xdc,
	0x38, 0xed, 0x7a, 0x7a, 0x0a, 0x58, 0x4b, 0x86, 0x52, 0x94, 0x27, 0x1c, 0x6b, 0x49, 0x19, 0xc4,
	0xa5, 0x55, 0xc2, 0x29, 0xc9, 0x70, 0x8a, 0x72, 0xc4, 0xe7, 0x92, 0x9e, 0x43, 0xd4, 0x9a, 0xae,
	0xd8, 0xb3, 0x20, 0x45, 0x39, 0xe6, 0x61, 0x6b, 0xba, 0xed, 0x0c, 0x7b, 0x16, 0x2e, 0xf0, 0x6e,
	0x80, 0x3b, 0x55, 0x15, 0x7b, 0x16, 0x8d, 0x70, 0xa7, 0xaa, 0xed, 0x0c, 0x7b, 0x46, 0x16, 0xe8,
	0x9d, 0x52, 0xdb, 0x62, 0xcf, 0xe2, 0x11, 0x4a, 0x6d, 0xb7, 0x33, 0xec, 0xd9, 0xc9, 0x02, 0xef,
	0xe8, 0x07, 0x00, 0xab, 0x1a, 0xa9, 0xac, 0xb8, 0xaf, 0x14, 0x5b, 0xa5, 0x41, 0xbe, 0x7e, 0xf7,
	0xea, 0xf2, 0xe9, 0xae, 0x7c, 0x31, 0xf0, 0x47, 0x66, 0x4a, 0x21, 0x6c, 0x44, 0xad, 0x18, 0xa4,
	0x28, 0x5f, 0x71, 0xaf, 0x07, 0x56, 0xfe, 0x14, 0x8e, 0xad, 0x47, 0x36, 0xe8, 0xec, 0x0b, 0xc0,
	0x43, 0x87, 0x83, 0xc3, 0x3c, 0x87, 0xa8, 0x34, 0x95, 0xb1, 0xfe, 0x2c, 0x09, 0x1f, 0x8b, 0xa1,
	0x4f, 0xa7, 0x7f, 0xab, 0xf9, 0x26, 0x83, 0xce, 0x4a, 0x20, 0xb7, 0xad, 0x14, 0xce, 0x4f, 0x71,
	0xba, 0x56, 0xbe, 0x0b, 0xe2, 0x5e, 0xd3, 0x0b, 0x20, 0xca, 0x9f, 0x9e, 0x61, 0xbf, 0xc4, 0x8b,
	0xff, 0x96, 0x18, 0x73, 0xe1, 0x93, 0x89, 0xbe, 0x04, 0x62, 0x55, 0x6d, 0x76, 0xc3, 0x88, 0x20,
	0x4f, 0xf8, 0x54, 0x65, 0x7f, 0x11, 0x90, 0x6f, 0x4e, 0xb8, 0x5f, 0x1d, 0x7d, 0x0d, 0xab, 0xb6,
	0x12, 0xbd, 0xb2, 0xc5, 0xf4, 0xe0, 0x90, 0x9f, 0x8c, 0xe0, 0x46, 0x3e, 0x64, 0x81, 0x8f, 0x65,
	0x11, 0x1c, 0xcb, 0x22, 0x3c, 0x96, 0x45, 0xf4, 0x28, 0x8b, 0x0b, 0x20, 0xa2, 0x74, 0xda, 0x34,
	0x8c, 0xa4, 0x41, 0x7e, 0x7a, 0xb0, 0xc2, 0x47, 0xff, 0x91, 0x4f, 0xa6, 0xb7, 0x6f, 0x80, 0x8c,
	0x84, 0xae, 0x21, 0xde, 0x7c, 0xfd, 0x7e, 0x7d, 0xb3, 0xb9, 0x3a, 0x7b, 0x46, 0x63, 0x08, 0xae,
	0x6e, 0x37, 0x67, 0xe8, 0x13, 0xbe, 0x0e, 0xee, 0x89, 0xff, 0xf9, 0xfd, 0xbf, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xaa, 0x41, 0xa8, 0x82, 0xbe, 0x02, 0x00, 0x00,
}
